version: "3.3"
services: 
  todo-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - ./src:/app/src
    test:
      build: 
        context: .
      environment:
        - CI=true
      command: npm run test 

       
    

